# Site settings
name: Kerzzi's Blog
email: kerzzi@outlook.com
author: Kerzzi
url: https://kerzzi-1.github.io/
#resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/Kerzzi/
baseurl: "/"
description: Actually, less is more!
meta_description: 刘铮;个人博客;kerzzi;柯子;叫我柯子就好;柯子的博客
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Kerzzi
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : yungentie
    duoshuo:
        short_name : kerzzi
    disqus :
        short_name : kerzzi
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
